# Generated by Django 5.1.7 on 2025-03-31 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='hotel_servi_name_62c43a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='hotel_servi_city_55ae6d_idx'), models.Index(fields=['state'], name='hotel_servi_state_a64a20_idx'), models.Index(fields=['country'], name='hotel_servi_country_d78cc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.PositiveIntegerField(help_text='ID from the Hotel service')),
                ('room_type_id', models.PositiveIntegerField(help_text='ID from the RoomType service')),
                ('date', models.DateField()),
                ('total_count', models.PositiveIntegerField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('available_count', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='hotel_servi_date_ba2993_idx'), models.Index(fields=['hotel_id'], name='hotel_servi_hotel_i_61ed57_idx'), models.Index(fields=['room_type_id'], name='hotel_servi_room_ty_9884a4_idx')],
                'unique_together': {('hotel_id', 'room_type_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('standard', 'Standard'), ('suite', 'Suite'), ('deluxe', 'Deluxe')], default='standard', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='hotel_servi_name_ec48c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('hotel_amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_hotels', to='hotel_service.amenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_amenities', to='hotel_service.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel'], name='hotel_servi_hotel_i_584f5b_idx'), models.Index(fields=['amenity'], name='hotel_servi_amenity_26368c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('promotion_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='hotel_service.roomtype')),
            ],
            options={
                'indexes': [models.Index(fields=['rate_date'], name='hotel_servi_rate_da_47cb71_idx'), models.Index(fields=['room_type'], name='hotel_servi_room_ty_ae2abc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotel_service.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_service.roomtype')),
            ],
            options={
                'indexes': [models.Index(fields=['capacity'], name='hotel_servi_capacit_148bde_idx'), models.Index(fields=['room_type'], name='hotel_servi_room_ty_b4ac7d_idx')],
            },
        ),
    ]
